# Site settings
title: Rutwik Hiwalkar
description: "Outcome of Letting my intrusive thoughts win"
baseurl: ""
url: "https://rutwikhdev.github.io"
twitter: "https://x.com/rutwiked"
github: "https://github.com/rutwikhdev"
linkedin: "https://www.linkedin.com/in/rutwikhdev/"

# Build settings
markdown: kramdown
permalink: /:title/

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

# Serene-style theme settings
name: Rutwik Hiwalkar
id: rutwikhdev
bio: "Outcome of letting my intrusive thoughts win..."
avatar: /assets/me-640.webp

links:
  - { name: GitHub, icon: github, url: "https://github.com/rutwikhdev" }
  - { name: X, icon: twitter, url: "https://x.com/rutwiked" }
  - { name: Linkedin, icon: linkedin, url: "https://www.linkedin.com/in/rutwikhdev/" }
  - { name: Email, icon: email, url: "mailto:rutwikhdev@gmail.com" }

sections:
  - { name: ~/posts, path: /posts, is_external: false }
  - { name: ~/about, path: /about, is_external: false }
  - { name: ~/resume.pdf, path: /resume.pdf, is_external: true }

blog_title: Posts
date_format: "%b %-d, %Y"
recent_max: 5
recent_more_text: "more »"

back_link_text: Back
footer_copyright: "© rutwik hiwalkar"
footer_credits: false
not_found_error_text: "404 Not Found"
not_found_recover_text: "« back to home »"

toc: true
back_to_top: true
